### ISSUE TITLE
May I ask if the total number of iterations is 200？200= repeat_kfold * len(val_id) * len(test_id)

### ISSUE THREAD

**Issue by Augenstern1120** [Vincent-ZHQ/CA-MSER#15]
I am a beginner and I think your paper and code are very ingenious. However, I have one more question and hope you can answer it.Thanks！
1What does True mean in the output result？2What does 31 31 mean？
True
31 31
![image](https://github.com/Vincent-ZHQ/CA-MSER/assets/143238177/7ac65c9b-e5c7-40c8-9561-cc9b7fb2310d)

**Comment by Vincent-ZHQ** [comment]
I appreciate your interest in our work. However, this is work done two years ago. I can no longer remember many details. The code, environment and server have been changed and are no longer maintained. When I uploaded my work, I made sure it worked properly. I strongly recommend reading the code first to familiarize yourself with the logic, and you can understand the code by referring to the outputs. I printed some results for Debug and did not remove them in the final version. The following are your answers to your questions. They could be found in the code after you read it.

https://github.com/Vincent-ZHQ/CA-MSER/blob/8c77cfe3ccc33983d3658e26dcf02b2dce63750c/train_ser.py#L500
https://github.com/Vincent-ZHQ/CA-MSER/blob/8c77cfe3ccc33983d3658e26dcf02b2dce63750c/train_ser.py#L508
