### ISSUE TITLE
Some questions for Speech Emotion Recognition

### ISSUE THREAD

**Issue by wangjialin97** [Vincent-ZHQ/CA-MSER#2]
Dear Professor,
    I am a master of Hebei University of Science and Technology,major in Computer Science and Technology.Your published paper,"Speech Emotion Recogition with Co-Attention based Multi-level Acoustic Information", gave me lots of inspirations,especially the feature extraction part and the feature fusion part.But I noticed that there is a part of source code had disappeared,named "feature_extraction".if it is convenient for you,could you please sent it to my email,2869294195@qq.com,I believe it will help me a lot.
Best Wishes,
Jialin
![File system](https://user-images.githubusercontent.com/60220081/164406346-1317e185-5c0d-462e-b563-122bc728352c.jpg)

**Comment by Vincent-ZHQ** [comment]
Hi, I have sent the code to you. You can refer to it.
Actually, the code of feature_extraction is not directly related to the run of this project. And we have made some changes to the code. When you run this project, you could refer to the provided extracted data.  [issue1](https://github.com/Vincent-ZHQ/CA-MSER/issues/1)

**Comment by BinhNguyen231** [comment]
> Hi, I have sent the code to you. You can refer to it. Actually, the code of feature_extraction is not directly related to the run of this project. And we have made some changes to the code. When you run this project, you could refer to the provided extracted data. [issue1](https://github.com/Vincent-ZHQ/CA-MSER/issues/1)

Hi Vincent, 
I'm Binh, a student of Hanoi University of Science and Technology in Viet Nam. I'm researching in SER for my project in University. Could you send me the code of feature_extraction to my email: _binhnn2301@gmail.com_
This will help me a lot. Thank you.

**Comment by neticle2012** [comment]
> Hi, I have sent the code to you. You can refer to it. Actually, the code of feature_extraction is not directly related to the run of this project. And we have made some changes to the code. When you run this project, you could refer to the provided extracted data. [issue1](https://github.com/Vincent-ZHQ/CA-MSER/issues/1)

Dear Professor,
I'm Yurun, a master student of The University of Tokyo in Japan. Could you please send me the code of feature_extraction.py to my mail: heyurun123@gmail.com ? I believe it will help me to understand how you extract the features from the raw data better. Thank you!
