### ISSUE TITLE
Request to offer data preprocess and feature extraction codes

### ISSUE THREAD

**Issue by happyjin** [Vincent-ZHQ/CA-MSER#3]
Dear M.Sc. Zou. 

Thank you very much for the fantastic work and open-source code on "Speech Emotion Recognition with Co-Attention based Multi-level Acoustic Information". However, the data preprocessing and feature extraction codes of the project are missing. Could you please send me data preprocessing and feature extraction codes to help me reimplement your work from scratch? It will accelerate the development of the speech emotion recognition field and I will respect it by carefully citing your work. My email address is [lijin.engineer@gmail.com](lijin.engineer@gmail.com).

Thanks & regards,

Jin Li

**Comment by Vincent-ZHQ** [comment]
Hi Jin. I have emailed it to you. Hope it is helpful for you!
