### ISSUE TITLE
about the extract_features code

### ISSUE THREAD

**Issue by wl1320310292** [Vincent-ZHQ/CA-MSER#4]
你好，请问可以分享一下文件预处理的代码吗？即extract_features.py。非常感谢!

Could you please send me data preprocessing and feature extraction codes?My email address is 1320310292@qq.com. Thank you very much！

**Comment by Hila954** [comment]
Hello, may I please receive the feature extraction codes as well? my email is hili4224@gmail.com. Thank you!

**Comment by csDevin** [comment]
Could you please send me the source code for data preprocessing and feature extraction, i.e. extract_features.py . My email is cydingcs@gmail.com.

**Comment by LikWix3068** [comment]
Could you please send me the source code for data preprocessing and feature extraction, i.e. extract_features.py . My email is likwix@163.com.  Thanks a lot!
