### ISSUE TITLE
Question about the extract_features code 

### ISSUE THREAD

**Issue by LikWix3068** [Vincent-ZHQ/CA-MSER#5]
Could you please send me the source code for data preprocessing and feature extraction, i.e. extract_features.py . My email is likwix@163.com. Thanks a lot!

**Comment by evanism123-bit** [comment]
Could you please send me the source code for data preprocessing and feature extraction, i.e. extract_features.py . My email is 1178580082@qq.com. Thanks a lot!

**Comment by lin329** [comment]
Could you please send me the source code for data preprocessing and feature extraction, i.e. extract_features.py . My email is [632977218@qq.com](mailto:632977218@qq.com). Thanks a lot!

**Comment by mywwwww** [comment]
Could you please send me the source code for data preprocessing and feature extraction, i.e. extract_features.py . My email is [2253465241@qq.com](mailto:2253465241@qq.com). Thanks a lot!
