### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by Janie1996** [Vincent-ZHQ/CA-MSER#6]
Could you please send me the source code for data preprocessing and feature extraction, i.e. extract_features.py . My email is [841497210@qq.com](mailto:841497210@qq.com). 
Thanks a lot!

**Comment by LISCARqaq** [comment]
I also want your source code for data preprocessing. How do you define the seg_labels? The IEMOCAP dataset only provides the  sentence label. My email is 1281387764@qq.com
Thanks a lot.

**Comment by xiaofucn** [comment]
Dear author, I also want your source code for data preprocessing and feature extraction. The IEMOCAP dataset only provides the sentence label. Could you please give me the related source code. My email is xiaofucn@163.com.
Thank you very much!

**Comment by angryman123** [comment]
Could you please send me the source code for data preprocessing and feature extraction? It may help me a lot to understand the whole project. My email is lonelymath@163.com. Thanks for your kind！

**Comment by lihm311** [comment]
Dear author, could you please send me the source code for data preprocessing and feature extraction, extract_features.py . It may help me a lot. My email is 1105033812@qq.com. Thanks a lot!

**Comment by surviveMiao** [comment]
Your project is very helpful to my research. Can you extract_ The features.py file was sent to me for learning, and I am very grateful. Email: 276920603@qq.com.

**Comment by Thatboy-cpu** [comment]
Hello, your idea is very good, I would like to know your method of data pre-processing, can you provide me the relevant code, it may help me in my research.Email:guojiayu2019@126.com

**Comment by Vincent-ZHQ** [comment]
Thank you for your interest. The code for data processing is available online now. It can be downloaded and used as a reference.
If you think our paper and code are useful for your research work. Please give us a star or cite our original paper. This will give us the motivation to continue to share our code. Thank you!

**Comment by Thatboy-cpu** [comment]
Thank you for sharing, you've done me a great favour, good luck with your work


| |
郭佳雨
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/21/2022 15:04 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Vincent-ZHQ/CA-MSER] Feature Extraction (Issue #6) |

Thank you for your interest. The code for data processing is available online now. It can be downloaded and used as a reference.
If you think our paper and code are useful for your research work. Please give us a star or cite our original paper. This will give us the motivation to continue to share our code. Thank you!
