### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by LISCARqaq** [Vincent-ZHQ/CA-MSER#7]
Hello, thanks for your great project! Could you please provide the code how to preprocess data from .wav file. I wonder how to make spectrogram with dimension (300*200), which was mentioned in the paper.

**Comment by Vincent-ZHQ** [comment]
Thank you for your interest. The code for data processing is available now. I think you can check the code to find the detail of your answer. Wish you the best! Thank you!
