### ISSUE TITLE
extract_features.py

### ISSUE THREAD

**Issue by Jingerkang** [Vincent-ZHQ/CA-MSER#8]
Dear author, I am conducting the SER project, and your project is helpful to me. But I found no extract_features.py file mentioned in your project. Could you please share the code? My email address is jingerkang@mail.hfut.edu.cn. Thank you very much.

**Comment by LISCARqaq** [comment]
> 

I try to write the feature extraction with torchaudio, but got bad performance. Have you done the experiment? And how was the result?

**Comment by Jingerkang** [comment]
The author provided the processed IEMOCAP dataset with pkl format. After parsing and visualizing the dataset, I got the input format of the Mel-spectrogram, MFCCs, and the raw audio signal. At first, the original audio signal was segmented into 3-second length clips (refer to the published paper&nbsp;Speech Emotion Recognition with Co-Attention based Multi-level Acoustic Information). All these input features were generated based on these clips.
For Mel-spectrogram, firstly, log-Mel-spectrogram was generated by using librosa.feature.melspectrogram() and librosa.power_to_db(). Then padded the log-Mel-spectrogram to 300 (hop-length was set to 10ms) along the time axis with 0. But I got nothing to know with other process of the audio signal, such as denoising.
For MFCCs, run librosa.feature.mfcc() and pad it to the specific length along the time axis with 0.
For raw audio signal, pad it to the length of 48000 with 0.
If you have further insights, I would be appreciated to know it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vincent-ZHQ/CA-MSER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月27日(星期二) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vincent-ZHQ/CA-MSER] extract_features.py (Issue #8)





   
I try to write the feature extraction with torchaudio, but got bad performance. Have you done the experiment? And how was the result?

**Comment by LISCARqaq** [comment]
> 

I used the spectrogram not the Mel-spectrogram. What is the shape of the Mel-spectrogram you extracted?
My method is as follow:
waveform, sr = torchaudio.load(wav_path, num_frames=16000*3)  # max length 3s
waveform = waveform.resize_(1, 48000)  # if less than 3s, padding to 3s
spec = torchaudio.compliance.kaldi.spectrogram(waveform, sample_frequency=16000, snip_edges=False, window_type='hamming')
I got the shape of spec (300, 257), but it is (300, 200) in the paper.
Have you used the provided processed data directly?
Thanks for your reply.

**Comment by Jingerkang** [comment]
The shape of the Mel-spectrogram I used is (300, 200). In librosa.feature.melspectrogram() method, the parameter n_mels controls the number of Mel bands, and this can be set to 200.


The inner function named&nbsp;_get_strided decides the shape of spectrogram. You can refer to&nbsp;https://pytorch.org/audio/stable/compliance.kaldi.html. Why not use Mel-spectrogram? The method torchaudio.transforms.Spectrogram() can generate Mel-spectrogram with specific number of Mel-bands, and you can set it to 200.


I did not use the provided data directly in my work.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vincent-ZHQ/CA-MSER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月27日(星期二) 中午1:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vincent-ZHQ/CA-MSER] extract_features.py (Issue #8)





   
I used the spectrogram not the Mel-spectrogram. What is the shape of the Mel-spectrogram you extracted?
 My method is as follow:
 waveform, sr = torchaudio.load(wav_path, num_frames=16000*3)  # max length 3s
 waveform = waveform.resize_(1, 48000)  # if less than 3s, padding to 3s
 spec = torchaudio.compliance.kaldi.spectrogram(waveform, sample_frequency=16000, snip_edges=False, window_type='hamming')
 I got the shape of spec (300, 257), but it is (300, 200) in the paper.
 Have you used the provided processed data directly?
 Thanks for your reply.

**Comment by CHEN-WDan** [comment]
Hi Vincent,
I'm Chen, a student of Taiyuan University of  Technology. I'm researching in SER for my project in University. Could you send me the code of feature_extraction to my email: chenweidan2020@163.com.
This will help me a lot. Thank you.

**Comment by surviveMiao** [comment]
Your project is very helpful to my research. Can you extract_ The features.py file was sent to me for learning, and I am very grateful. Email: 276920603@qq.com.

**Comment by Vincent-ZHQ** [comment]
Thank you for your interest. The code for data processing is available online now. It can be downloaded and used as a reference.
If you think our paper and code are useful for your research work. Please give us a star or cite our original paper. This will give us the motivation to continue to share our code.  Thank you!
